import { emptyDoc, textDoc } from './richtext';
import { PROTOTYPE_NOW, fromZoned } from './dates';
import type {
  AppState,
  CalendarEvent,
  CalendarSource,
  DatabaseItem,
  FocusSession,
  NotionSource,
  Project,
  Tag,
  Task,
} from './types';

const TZ = 'America/New_York';

function t(date: string, h: number, m: number): string {
  return fromZoned(date, h, m, TZ);
}

export const CALENDARS: CalendarSource[] = [
  {
    id: 'cal-work',
    name: 'Work',
    kind: 'work',
    color: '#3d6b8a',
    visible: true,
    account: 'maya@notion.so',
    health: 'saved',
    timeZone: TZ,
  },
  {
    id: 'cal-personal',
    name: 'Personal',
    kind: 'personal',
    color: '#8a5a3d',
    visible: true,
    account: 'maya@personal.mail',
    health: 'saved',
    timeZone: TZ,
  },
  {
    id: 'cal-team',
    name: 'Design team',
    kind: 'shared',
    color: '#5a6b4a',
    visible: true,
    account: 'design@notion.so',
    health: 'saved',
    timeZone: TZ,
  },
];

export const NOTION_SOURCES: NotionSource[] = [
  {
    id: 'db-launch',
    name: 'Launch calendar',
    visible: true,
    color: '#7a5a8a',
    isTaskSource: false,
    dateProperty: 'Ship date',
    health: 'saved',
  },
  {
    id: 'db-content',
    name: 'Content calendar',
    visible: true,
    color: '#6a7a5a',
    isTaskSource: false,
    dateProperty: 'Publish',
    health: 'saved',
  },
  {
    id: 'db-personal-tasks',
    name: 'Personal Tasks',
    visible: false,
    color: '#c45c26',
    isTaskSource: true,
    dateProperty: 'Due',
    mapped: {
      title: 'Name',
      status: 'Status',
      completedStatus: 'Done',
      due: 'Due',
      priority: 'Priority',
      project: 'Project',
      tags: 'Tags',
    },
    health: 'saved',
  },
];

export const PROJECTS: Project[] = [
  { id: 'proj-redesign', name: 'Calendar Redesign', archived: false, order: 0, color: '#c45c26' },
  { id: 'proj-launch', name: 'Launch', archived: false, order: 1, color: '#7a5a8a' },
  { id: 'proj-personal', name: 'Personal', archived: false, order: 2, color: '#8a5a3d' },
];

export const TAGS: Tag[] = [
  { id: 'tag-research', name: 'research' },
  { id: 'tag-writing', name: 'writing' },
  { id: 'tag-meeting', name: 'meeting-prep' },
  { id: 'tag-ops', name: 'ops' },
];

export const TASKS: Task[] = [
  {
    kind: 'task',
    id: 'task-inbox-capture',
    title: 'Capture interview notes from last usability round',
    completed: false,
    projectId: 'proj-redesign',
    tagIds: ['tag-research'],
    priority: 'medium',
    description: emptyDoc(),
    links: [],
    createdAt: '2026-09-16T15:10:00.000Z',
    updatedAt: '2026-09-16T15:10:00.000Z',
    syncState: 'saved',
    activity: [{ id: 'a1', at: '2026-09-16T15:10:00.000Z', label: 'Created in Inbox' }],
  },
  {
    kind: 'task',
    id: 'task-research-synth',
    title: 'Write research synthesis',
    completed: false,
    projectId: 'proj-redesign',
    tagIds: ['tag-research', 'tag-writing'],
    priority: 'high',
    description: textDoc(
      'Pull quotes from the five calendar-plus-tasks interviews.\n\nDraft lives in Notion: https://www.notion.so/research-synthesis',
    ),
    links: [
      {
        id: 'lnk-synth',
        url: 'https://www.notion.so/research-synthesis',
        label: 'Synthesis page',
        kind: 'notion',
      },
    ],
    createdAt: '2026-09-14T12:00:00.000Z',
    updatedAt: '2026-09-16T18:00:00.000Z',
    syncState: 'saved',
    activity: [
      { id: 'a2', at: '2026-09-14T12:00:00.000Z', label: 'Created' },
      { id: 'a3', at: '2026-09-16T18:00:00.000Z', label: 'Scheduled focus on Wednesday' },
    ],
  },
  {
    kind: 'task',
    id: 'task-faq',
    title: 'Prepare launch FAQ',
    completed: false,
    projectId: 'proj-launch',
    tagIds: ['tag-writing'],
    priority: 'high',
    deadline: '2026-09-19',
    description: textDoc('Need both customer-facing and sales-facing versions before Friday.'),
    links: [],
    createdAt: '2026-09-12T10:00:00.000Z',
    updatedAt: '2026-09-15T16:00:00.000Z',
    syncState: 'saved',
    activity: [{ id: 'a4', at: '2026-09-12T10:00:00.000Z', label: 'Created with Friday deadline' }],
  },
  {
    kind: 'task',
    id: 'task-grocery',
    title: 'Order groceries for the weekend',
    completed: false,
    projectId: 'proj-personal',
    tagIds: [],
    priority: 'low',
    deadline: '2026-09-17',
    description: emptyDoc(),
    links: [],
    createdAt: '2026-09-16T20:00:00.000Z',
    updatedAt: '2026-09-16T20:00:00.000Z',
    syncState: 'saved',
    activity: [{ id: 'a5', at: '2026-09-16T20:00:00.000Z', label: 'Created' }],
  },
  {
    kind: 'task',
    id: 'task-brief',
    title: 'Share critique brief with the design team',
    completed: false,
    projectId: 'proj-redesign',
    tagIds: ['tag-meeting'],
    priority: 'medium',
    deadline: '2026-09-18',
    description: emptyDoc(),
    links: [],
    createdAt: '2026-09-15T09:00:00.000Z',
    updatedAt: '2026-09-15T09:00:00.000Z',
    syncState: 'saved',
    activity: [{ id: 'a6', at: '2026-09-15T09:00:00.000Z', label: 'Created' }],
  },
  {
    kind: 'task',
    id: 'task-failed',
    title: 'Upload recording of Monday planning',
    completed: false,
    projectId: 'proj-redesign',
    tagIds: ['tag-ops'],
    priority: 'low',
    description: textDoc('File is on the laptop. Needs to land in the research drive.'),
    links: [],
    createdAt: '2026-09-16T21:00:00.000Z',
    updatedAt: '2026-09-17T12:10:00.000Z',
    syncState: 'needs_attention',
    activity: [
      { id: 'a7', at: '2026-09-16T21:00:00.000Z', label: 'Created' },
      { id: 'a8', at: '2026-09-17T12:10:00.000Z', label: 'Save failed — needs attention' },
    ],
  },
  {
    kind: 'task',
    id: 'task-done-interviews',
    title: 'Schedule remaining research interviews',
    completed: true,
    completedAt: '2026-09-15T19:00:00.000Z',
    projectId: 'proj-redesign',
    tagIds: ['tag-research'],
    priority: 'medium',
    deadline: '2026-09-15',
    description: emptyDoc(),
    links: [],
    createdAt: '2026-09-10T14:00:00.000Z',
    updatedAt: '2026-09-15T19:00:00.000Z',
    syncState: 'saved',
    activity: [{ id: 'a9', at: '2026-09-15T19:00:00.000Z', label: 'Completed' }],
  },
  {
    kind: 'task',
    id: 'task-unscheduled-no-deadline',
    title: 'Sketch empty-state for the task panel',
    completed: false,
    projectId: undefined,
    tagIds: [],
    priority: 'none',
    description: emptyDoc(),
    links: [],
    createdAt: '2026-09-17T11:00:00.000Z',
    updatedAt: '2026-09-17T11:00:00.000Z',
    syncState: 'saved',
    activity: [{ id: 'a10', at: '2026-09-17T11:00:00.000Z', label: 'Captured without a deadline' }],
  },
];

export const EVENTS: CalendarEvent[] = [
  {
    kind: 'event',
    id: 'evt-critique',
    title: 'Design critique',
    start: t('2026-09-15', 10, 0),
    end: t('2026-09-15', 11, 0),
    allDay: false,
    calendarId: 'cal-team',
    attendees: [
      { id: 'p1', name: 'Jordan Lee', email: 'jordan@notion.so', status: 'accepted' },
      { id: 'p2', name: 'Sam Okonkwo', email: 'sam@notion.so', status: 'accepted' },
    ],
    organizer: 'Maya Chen',
    location: 'Studio B',
    conferencingUrl: 'https://meet.google.com/cal-critique',
    description: textDoc('Bring the latest calendar blocks. Join: https://meet.google.com/cal-critique'),
    links: [
      {
        id: 'lnk-meet',
        url: 'https://meet.google.com/cal-critique',
        label: 'Meet link',
        kind: 'meeting',
      },
    ],
    availability: 'busy',
    visibility: 'default',
    timeZone: TZ,
    createdAt: '2026-09-08T10:00:00.000Z',
    updatedAt: '2026-09-08T10:00:00.000Z',
    syncState: 'saved',
  },
  {
    kind: 'event',
    id: 'evt-sync',
    title: 'Product sync',
    start: t('2026-09-16', 9, 0),
    end: t('2026-09-16', 10, 0),
    allDay: false,
    calendarId: 'cal-work',
    attendees: [{ id: 'p3', name: 'Alex Rivera', email: 'alex@notion.so', status: 'accepted' }],
    organizer: 'Alex Rivera',
    conferencingUrl: 'https://zoom.us/j/84729103',
    description: textDoc('Weekly priorities. Zoom: https://zoom.us/j/84729103'),
    links: [
      { id: 'lnk-zoom', url: 'https://zoom.us/j/84729103', label: 'Zoom', kind: 'meeting' },
    ],
    availability: 'busy',
    visibility: 'default',
    timeZone: TZ,
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    syncState: 'saved',
  },
  {
    kind: 'event',
    id: 'evt-1on1',
    title: '1:1 with Maya',
    start: t('2026-09-17', 14, 0),
    end: t('2026-09-17', 14, 30),
    allDay: false,
    calendarId: 'cal-work',
    attendees: [{ id: 'p4', name: 'Maya Chen', email: 'maya@notion.so', status: 'accepted' }],
    organizer: 'Maya Chen',
    location: 'Floor 4 nook',
    description: emptyDoc(),
    links: [],
    availability: 'busy',
    visibility: 'private',
    timeZone: TZ,
    createdAt: '2026-09-02T10:00:00.000Z',
    updatedAt: '2026-09-02T10:00:00.000Z',
    syncState: 'saved',
  },
  {
    kind: 'event',
    id: 'evt-allhands',
    title: 'All-hands',
    start: t('2026-09-18', 11, 0),
    end: t('2026-09-18', 12, 0),
    allDay: false,
    calendarId: 'cal-work',
    attendees: [],
    organizer: 'Office of the CEO',
    conferencingUrl: 'https://zoom.us/j/111222333',
    description: emptyDoc(),
    links: [{ id: 'lnk-ah', url: 'https://zoom.us/j/111222333', label: 'All-hands Zoom', kind: 'meeting' }],
    availability: 'busy',
    visibility: 'default',
    timeZone: TZ,
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
    syncState: 'saved',
  },
  {
    kind: 'event',
    id: 'evt-dinner',
    title: 'Dinner with Alex',
    start: t('2026-09-18', 19, 0),
    end: t('2026-09-18', 21, 0),
    allDay: false,
    calendarId: 'cal-personal',
    attendees: [{ id: 'p5', name: 'Alex Rivera', email: 'alex@personal.mail', status: 'accepted' }],
    location: 'Lilac, Brooklyn',
    description: emptyDoc(),
    links: [],
    availability: 'busy',
    visibility: 'private',
    timeZone: TZ,
    createdAt: '2026-09-10T10:00:00.000Z',
    updatedAt: '2026-09-10T10:00:00.000Z',
    syncState: 'saved',
  },
  {
    kind: 'event',
    id: 'evt-ooo',
    title: 'Focus Friday (company)',
    start: t('2026-09-18', 0, 0),
    end: t('2026-09-19', 0, 0),
    allDay: true,
    calendarId: 'cal-work',
    attendees: [],
    description: emptyDoc(),
    links: [],
    availability: 'free',
    visibility: 'default',
    timeZone: TZ,
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    syncState: 'saved',
  },
];

export const FOCUS_SESSIONS: FocusSession[] = [
  {
    kind: 'focus_session',
    id: 'focus-synth-wed',
    taskId: 'task-research-synth',
    start: t('2026-09-16', 10, 0),
    end: t('2026-09-16', 11, 30),
    note: 'Outline first, then quotes.',
    blocksAvailability: true,
    calendarId: 'cal-work',
    sessionCompleted: false,
    createdAt: '2026-09-15T18:00:00.000Z',
    updatedAt: '2026-09-15T18:00:00.000Z',
    syncState: 'saved',
  },
  {
    kind: 'focus_session',
    id: 'focus-faq-thu',
    taskId: 'task-faq',
    start: t('2026-09-17', 10, 0),
    end: t('2026-09-17', 11, 30),
    blocksAvailability: true,
    calendarId: 'cal-work',
    sessionCompleted: false,
    createdAt: '2026-09-16T12:00:00.000Z',
    updatedAt: '2026-09-16T12:00:00.000Z',
    syncState: 'saved',
  },
  {
    kind: 'focus_session',
    id: 'focus-faq-fri',
    taskId: 'task-faq',
    start: t('2026-09-18', 9, 0),
    end: t('2026-09-18', 10, 30),
    blocksAvailability: true,
    calendarId: 'cal-work',
    sessionCompleted: false,
    createdAt: '2026-09-16T12:05:00.000Z',
    updatedAt: '2026-09-16T12:05:00.000Z',
    syncState: 'saved',
  },
  {
    kind: 'focus_session',
    id: 'focus-interviews-past',
    taskId: 'task-done-interviews',
    start: t('2026-09-15', 15, 0),
    end: t('2026-09-15', 16, 0),
    blocksAvailability: true,
    calendarId: 'cal-work',
    sessionCompleted: true,
    createdAt: '2026-09-14T10:00:00.000Z',
    updatedAt: '2026-09-15T16:05:00.000Z',
    syncState: 'saved',
  },
];

export const DATABASE_ITEMS: DatabaseItem[] = [
  {
    kind: 'database_item',
    id: 'dbitem-beta',
    title: 'Beta announcement',
    databaseId: 'db-launch',
    start: t('2026-09-22', 0, 0),
    allDay: true,
    properties: { Status: 'Scheduled', Owner: 'Launch' },
    url: 'https://www.notion.so/launch-beta-announcement',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
    syncState: 'saved',
  },
  {
    kind: 'database_item',
    id: 'dbitem-blog',
    title: 'Blog: Planning vs doing',
    databaseId: 'db-content',
    start: t('2026-09-18', 0, 0),
    allDay: true,
    properties: { Status: 'Draft', Channel: 'Blog' },
    url: 'https://www.notion.so/content-planning-vs-doing',
    createdAt: '2026-09-05T10:00:00.000Z',
    updatedAt: '2026-09-05T10:00:00.000Z',
    syncState: 'saved',
  },
];

export function createSeedState(): AppState {
  return {
    now: PROTOTYPE_NOW,
    timeZone: TZ,
    view: 'week',
    focusedDate: '2026-09-17',
    mobileTab: 'calendar',
    calendars: CALENDARS.map((c) => ({ ...c })),
    notionSources: NOTION_SOURCES.map((s) => ({ ...s })),
    projects: PROJECTS.map((p) => ({ ...p })),
    tags: TAGS.map((t) => ({ ...t })),
    tasks: TASKS.map((t) => ({ ...t, tagIds: [...t.tagIds], links: t.links.map((l) => ({ ...l })), activity: t.activity.map((a) => ({ ...a })) })),
    events: EVENTS.map((e) => ({ ...e, attendees: [...e.attendees], links: e.links.map((l) => ({ ...l })) })),
    focusSessions: FOCUS_SESSIONS.map((s) => ({ ...s })),
    databaseItems: DATABASE_ITEMS.map((d) => ({ ...d, properties: { ...d.properties } })),
    selected: null,
    rightMode: 'tasks',
    taskView: 'inbox',
    filters: { showCompleted: false },
    search: '',
    taskScroll: 0,
    detailsReturn: null,
    leftCollapsed: false,
    rightCollapsed: false,
    leftWidth: 248,
    rightWidth: 360,
    overlay: null,
    toast: null,
    analytics: [],
    failedChanges: [
      {
        id: 'fail-upload',
        objectId: 'task-failed',
        objectKind: 'task',
        action: 'update',
        previousJson: JSON.stringify(TASKS.find((t) => t.id === 'task-failed')),
        pendingJson: JSON.stringify(TASKS.find((t) => t.id === 'task-failed')),
        message: 'Could not reach Personal Tasks in Notion. The task is still here.',
        createdAt: '2026-09-17T12:10:00.000Z',
      },
    ],
    simulateNextSaveFailure: false,
    accountHealth: {
      label: 'Personal Tasks · Notion',
      state: 'needs_attention',
      detail: '1 change needs attention',
    },
    undo: null,
  };
}
